apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cestc.cn/description: sec1
    deployment.kubernetes.io/revision: '5'
    cestc.cn/alias-name: ''
  labels:
    app: sec1
  name: sec1
  namespace: dlxjs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sec1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sec1
    spec:
      affinity: {}
      containers:
        - image: registry-inner.cqxw2q.cqxw2cloud.com/dlxjs/sec:v2.0
          imagePullPolicy: IfNotPresent
          name: cecloud-container-11123
          ports:
            - containerPort: 8998
              name: tcp-8998
              protocol: TCP
          resources:
            limits:
              memory: 5000Mi
              cpu: '2'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: host-time
