python:
  path:
    magnetic_global: F:\code-sw\chaos_submit\magnetic_global.py   #全球磁场分布算法
    orbital_magnetic: F:\code-sw\chaos_submit\magnetic_orbit.py   #轨道磁场分布算法
    atmosphere_density: /export/yuechao_cal/atm_density/msis_simu.py  #大气密度算法
    single_event_effects: /export/yuechao_cal/Single_events/seu_cal.py  #单粒子效应
    radiation_dose: /export/yuechao_cal/does_depth/does.py   #卫星辐射总剂量计算评估

picture:
  path:
    magnetic_global: F:\code-sw\magnetic_global\      #全球磁场分布图片存储路径
  url:
    magnetic_global: /png/magnetic_global/             #全球磁场分布图片映射路径

#配置文件路径
piesat:
  profile: E:/work/xw/server/fileServer/
  ip: 127.0.0.1 #配置文件服务ip,对应profile所在位置
  port: 9999 #端口
  tecStations: TEC/stations/ #TEC全国站点出图位置
  tecTimes: TEC/time/ #TEC时间段绘图数据
  s4Stations: S4/stations/ #闪烁指数全国站点出图位置
  s4Times: S4/time/ #闪烁指数时间段绘图数据
  roti: ROTI/ #ROTI算法结果存储位置
  secondDir: maps/Medium/ # TEC、ROTI算法二级目录