spring:
  mvc:
    servlet:
      path: /sec
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: dm.jdbc.driver.DmDriver
      url: jdbc:dm://kjsf-dm-pod.kjsf.svc.cluster.local:5236/SDC?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: SDC
    password: sdc123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

python:
  path:
    config: /tmp/lizw/chaos_submit/xw.ini
    magnetic_global: /tmp/lizw/chaos_submit/magnetic_global_V1.py   #全球磁场分布算法
    orbital_magnetic: /tmp/lizw/chaos_submit/magnetic_orbit.py   #轨道磁场分布算法
    atmosphere_density: /tmp/yuechao/atm_density/msis_simu.py  #大气密度算法
    single_event_effects: /tmp/yuechao/辐射剂量/seu/Single_events/seu_cal.py  #单粒子效应
    radiation_dose: /tmp/yuechao/辐射剂量/does_depth/does.py   #卫星辐射总剂量计算评估
    global_radiation_env: /tmp/yuechao/辐射环境/SRAD/global_radiation/global_radiation.py   #全球辐射环境算法
    orbit_reduction: /tmp/yuechao/轨道衰变效应/orbit_reduction/orbit_reduction.py   #轨道衰变效应算法
    satellite_radiation_env: /tmp/wrry/pythonPlot/global_radiation_plot.py   #卫星辐射环境算法
    cross_anomaly: /tmp/wrry/AP8AE8/SatCrossSAATime/sat_cross_SAA_time.py   #穿越南大西洋异常区算法

picture:
  path:
    magnetic_global: /export/magnetic_global/     #全球磁场分布图片存储路径
    global_radiation_env: /tmp/yuechao/辐射环境/SRAD/AP8AE8/     #全球辐射环境图片存储路径
    satellite_radiation_env: /tmp/wrry/AP8AE8/     #全球辐射环境图片存储路径
  url:
    magnetic_global: /png/magnetic_global/             #全球磁场分布图片映射路径
    global_radiation_env: /png/global_radiation_env/             #全球辐射环境图片映射路径
    satellite_radiation_env: /png/satellite_radiation_env/             #全球辐射环境图片映射路径

#python docker
remote:
  ip: 169.254.148.128
  port: 8026
  user_name: root
  password: 123456

#配置文件路径
piesat:
  profile: /sec/
  weekPngPy: algorithm/weekpng/analyse_t.py #周报算法图
  weekPngIni: algorithm/weekpng/xw.ini #周报算法数据库配置
  tecStationPy: algorithm/stationtecpng/TEC_keshihua_03_png_creation.py # 全国站点二维算法脚本
  tecStations: TEC/stations/ #TEC全国站点出图位置
  tecGLStationPy: algorithm/tecpng/TEC/parameter_maps.py #TEC全球站点三维算法脚本
  rotiGLStationPy: algorithm/roti/ROTI/parameter_maps.py #TEC全球站点三维算法脚本
  tecTimes: TEC/time/ #TEC时间段绘图数据
  s4Stations: S4/stations/ #闪烁指数全国站点出图位置
  s4Times: S4/time/ #闪烁指数时间段绘图数据
  roti: ROTI/ #ROTI算法结果存储位置
  secondDir: maps/Medium/ # TEC、ROTI算法二级目录

minio:
  endpoint: http://172.6.10.34:9000
  accesskey: minioadmin
  secretkey: miniostorage
  bucketName: htht
