server:
  port: 8998

spring:
  mvc:
    servlet:
      path: /sec
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: dm.jdbc.driver.DmDriver
    url: jdbc:dm://127.0.0.1:5236/SDC?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: SDC
    password: sdc123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

kjyy:
  module: sec
  db:
    type: dm
    create_time: createTime
    update_time: updateTime
  date:
    format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    cn.piesat.sec: debug
#配置报文文件路径
piesat:
  profile: E:/work/xw/server/fileServer/
