DROP TABLE IF EXISTS "SDC"."SEC_PARTICLE_FLUX";
CREATE TABLE "SDC"."SEC_PARTICLE_FLUX"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"P10" DOUBLE,
"P50" DOUBLE,
"P100" DOUBLE,
"E2" DOUBLE,
"PDIFF1" DOUBLE,
"PDIFF2A" DOUBLE,
"PDIFF2B" DOUBLE,
"PDIFF3" DOUBLE,
"PDIFF4" DOUBLE,
"PDIFF5" DOUBLE,
"PDIFF6" DOUBLE,
"PDIFF7" DOUBLE,
"PDIFF8A" DOUBLE,
"PDIFF8B" DOUBLE,
"PDIFF8C" DOUBLE,
"PDIFF9" DOUBLE,
"PDIFF10" DOUBLE,
"TIME" DATETIME(3),
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "SDC", CLUSTERBTR) ;
COMMENT ON TABLE "SDC"."SEC_PARTICLE_FLUX" IS '高能粒子通量数据';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."ID" IS 'ID主键';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."P10" IS '卫星轨道监测到的≥10MeV质子积分通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."P50" IS '卫星轨道监测到的≥50MeV质子积分通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."P100" IS '卫星轨道监测到的≥100MeV质子积分通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."E2" IS '卫星轨道监测到的≥2MeV电子积分通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF1" IS '卫星轨道监测到的1020-1860keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF2A" IS '卫星轨道监测到的1900-2300keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF2B" IS '卫星轨道监测到的2310-3340keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF3" IS '卫星轨道监测到的3400-6480keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF4" IS '卫星轨道监测到的5840-11000keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF5" IS '卫星轨道监测到的11640-23270keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF6" IS '卫星轨道监测到的25900-38100keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF7" IS '卫星轨道监测到的40300-73400keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF8A" IS '卫星轨道监测到的83700-98500keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF8B" IS '卫星轨道监测到的99900-118000keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF8C" IS '卫星轨道监测到的115000-143000keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF9" IS '卫星轨道监测到的160000-242000keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."PDIFF10" IS '卫星轨道监测到的276000-404000keV质子通量';
COMMENT ON COLUMN "SDC"."SEC_PARTICLE_FLUX"."TIME" IS '时间（UTC）';
commit;