CREATE VIEW "SDC"."V_ALL_ALARM" AS
(
(select ID, UNIT_ID, DEVICE_ID, PUBLISH_TIME, THRESHOLD_TIME, CONTENT, LEVEL,OVERVIEW,'CODE001' as code FROM SEC_XRAY_ALARM)
union all
(select ID, UNIT_ID, DEVICE_ID, PUBLISH_TIME, THRESHOLD_TIME, CONTENT, LEVEL,OVERVIEW,'CODE002' as code FROM SEC_DST_ALARM)
union all
(select ID, UNIT_ID, DEVICE_ID, PUBLISH_TIME, THRESHOLD_TIME, CONTENT, LEVEL,OVERVIEW,'CODE003' as code FROM SEC_PROTON_ALARM)
union all
(select ID, UNIT_ID, DEVICE_ID, PUBLISH_TIME, THRESHOLD_TIME, CONTENT, LEVEL,OVERVIEW,'CODE004' as code FROM SEC_ELE_ALARM)
)